import Head from 'next/head'
import {HomeComponent} from '../components/HomeComponent';

export default function Home() {
  return (
    <>
      <Head>
        <title>sors.software - bespoke software development</title>
        {/*<meta name="description" content="Generated by create next app" />*/}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*<p>soon.</p>*/}

      <HomeComponent />
    </>
  )
}
